//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace j2GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("j2GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _120x75_down {
            get {
                object obj = ResourceManager.GetObject("_120x75_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _120x75_Left_Arrow_Down {
            get {
                object obj = ResourceManager.GetObject("_120x75_Left_Arrow_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _120x75_Left_Arrow_Norm {
            get {
                object obj = ResourceManager.GetObject("_120x75_Left_Arrow_Norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _120x75_normal {
            get {
                object obj = ResourceManager.GetObject("_120x75_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _120x75_Right_Arrow_Down {
            get {
                object obj = ResourceManager.GetObject("_120x75_Right_Arrow_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _120x75_Right_Arrow_Norm {
            get {
                object obj = ResourceManager.GetObject("_120x75_Right_Arrow_Norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _120x75_scroll_down_down {
            get {
                object obj = ResourceManager.GetObject("_120x75_scroll_down_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _120x75_scroll_down_normal {
            get {
                object obj = ResourceManager.GetObject("_120x75_scroll_down_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _120x75_scroll_up_down {
            get {
                object obj = ResourceManager.GetObject("_120x75_scroll_up_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _120x75_scroll_up_normal {
            get {
                object obj = ResourceManager.GetObject("_120x75_scroll_up_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _213x75_down {
            get {
                object obj = ResourceManager.GetObject("_213x75_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _213x75_normal {
            get {
                object obj = ResourceManager.GetObject("_213x75_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _213x75_scrolldown_normal {
            get {
                object obj = ResourceManager.GetObject("_213x75_scrolldown_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _213x75_scrollup_down {
            get {
                object obj = ResourceManager.GetObject("_213x75_scrollup_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _213x75_scrollup_normal {
            get {
                object obj = ResourceManager.GetObject("_213x75_scrollup_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _213x75scrolldown_down {
            get {
                object obj = ResourceManager.GetObject("_213x75scrolldown_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _442x75_down {
            get {
                object obj = ResourceManager.GetObject("_442x75_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _442x75_highlighted {
            get {
                object obj = ResourceManager.GetObject("_442x75_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _442x75_normal {
            get {
                object obj = ResourceManager.GetObject("_442x75_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _480x680_Background {
            get {
                object obj = ResourceManager.GetObject("_480x680_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _75x75_check_down {
            get {
                object obj = ResourceManager.GetObject("_75x75_check_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _75x75_radio_down {
            get {
                object obj = ResourceManager.GetObject("_75x75_radio_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _75x75_radio_normal {
            get {
                object obj = ResourceManager.GetObject("_75x75_radio_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abaxis_logo {
            get {
                object obj = ResourceManager.GetObject("abaxis_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Advanced_Icon {
            get {
                object obj = ResourceManager.GetObject("Advanced_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlarmSettings_Icon {
            get {
                object obj = ResourceManager.GetObject("AlarmSettings_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArchiveRefRanges_Icon {
            get {
                object obj = ResourceManager.GetObject("ArchiveRefRanges_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DataFormat_Icon {
            get {
                object obj = ResourceManager.GetObject("DataFormat_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DateTime_Icon {
            get {
                object obj = ResourceManager.GetObject("DateTime_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FactoryDefaults_Icon {
            get {
                object obj = ResourceManager.GetObject("FactoryDefaults_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FactorySettings_Icon {
            get {
                object obj = ResourceManager.GetObject("FactorySettings_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FactorySettingsRD_Icon {
            get {
                object obj = ResourceManager.GetObject("FactorySettingsRD_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Info_Icon {
            get {
                object obj = ResourceManager.GetObject("Info_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap J2vs2_step1 {
            get {
                object obj = ResourceManager.GetObject("J2vs2_step1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap J2vs2_step2 {
            get {
                object obj = ResourceManager.GetObject("J2vs2_step2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap J2vs2_step3 {
            get {
                object obj = ResourceManager.GetObject("J2vs2_step3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Language_Icon {
            get {
                object obj = ResourceManager.GetObject("Language_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LessSettings_Icon {
            get {
                object obj = ResourceManager.GetObject("LessSettings_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoreSettings_Icon {
            get {
                object obj = ResourceManager.GetObject("MoreSettings_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrinterSettings_Icon {
            get {
                object obj = ResourceManager.GetObject("PrinterSettings_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Recall_Icon {
            get {
                object obj = ResourceManager.GetObject("Recall_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RefRanges_Icon {
            get {
                object obj = ResourceManager.GetObject("RefRanges_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScreenSettings_Icon {
            get {
                object obj = ResourceManager.GetObject("ScreenSettings_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Security_Icon {
            get {
                object obj = ResourceManager.GetObject("Security_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings_Icon {
            get {
                object obj = ResourceManager.GetObject("Settings_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SoftwareUpdate_Icon {
            get {
                object obj = ResourceManager.GetObject("SoftwareUpdate_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SplashRotor {
            get {
                object obj = ResourceManager.GetObject("SplashRotor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Units_Icon {
            get {
                object obj = ResourceManager.GetObject("Units_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WhoAmI_Icon {
            get {
                object obj = ResourceManager.GetObject("WhoAmI_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
