#ifndef _STARTUP_INCLUDE_FFILS_H_
#define _STARTUP_INCLUDE_FILES_H_
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <msgqueue.h>
#include <errno.h>
#include <ctype.h>
#include <winsock2.h>
#include <winioctl.h>
#include <ntddndis.h>
#include <iptypes.h>
#include <iphlpapi.h>
#include <pnp.h>

#include "AnalysisMessages.h"
#include "AstmMessages.h"
#include "BarcodeData.h"
#include "CalcBfds.h"
#include "CalcResultsMessages.h"
#include "CalData.h"
#include "CommonDefines.h"
#include "CounterData.h"
#include "EngineCommMessages.h"
#include "FtdiConfig.h"
#include "ftdi.h"
#include "Epcs.h"
#include "ErrLoggerMessages.h"
#include "GetThumbKeyMode.h"
#include "GuiMessages.h"
#include "Hardware.h"
#include "HardwareData.h"
#include "HeaterControlMessages.h"
#include "AStrings.h"
#include "LogErr.h"
#include "MountThumbDrive.h"
#include "OrdersData.h"
#include "ParseCounters.h"
#include "ParseExpirys.h"
#include "ParseFactory.h"
#include "ParseHardware.h"
#include "ParseRefRanges.h"
#include "ParseSettings.h"
#include "ParseSystem.h"
#include "ParseUnits.h"
#include "RawData.h"
#include "AmsData.h"
#include "RecallMessages.h"
#include "RefRanges.h"
#include "ResultsData.h"
#include "ResultsDb.h"
#include "RocData.h"
#include "SerialCommMessages.h"
#include "SettingsMessages.h"
#include "Shmem.h"
//#include "State.h"
#include "StartupMessages.h"
#include "SystemError.h"
#include "SystemErrorNums.h"
#include "TranslateUtf.h"
#include "Units.h"
#include "VersionData.h"
#include "SystemData.h"
#include "Eeprom.h"
#include "SetExpireTime.h"
#include "Startup.h"
#include "NetWorkSettings.h"
#include "CpuTempMonitor.h"
#include "ErrorProcessMessages.h"
#include "ParseHL7Configuration.h"
#include "PrinterMessages.h"
#include "CleanWindowsCeDatabase.h"
#endif
